#!/bin/sh
CLASSPATH=src:test:config:data

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

RLWRAP=`which rlwrap`
if [ ! -x "$RLWRAP" ] || [ "$RLWRAP" = "" ]; then
    RLWRAP=""
    JLINE=jline.ConsoleRunner
    if [ "$OSTYPE" = "cygwin" ]; then
        JLINE="-Djline.terminal=jline.UnixTerminal jline.ConsoleRunner"
        CYGWIN_JLINE=y
    fi
else
    JLINE=""
    # Test to see if rlwrap supports custom quote chars
    rlwrap -m -q '"' echo "hi" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        RLWRAP="$RLWRAP -m -q '\"'"
    fi
fi

$RLWRAP java -Xmx1G -cp $CLASSPATH $JLINE clojure.main -i script/run.clj -r
